[package]
name = "jbrowselistener"
version = "0.1.0"
authors = ["Archina Void <archina5thrider@gmail.com>"]
edition = "2018"

[dependencies]
serde="*"
serde_derive="*"
serde_json = "*"
amiquip = { version = "0.4", default-features = false }